### PR TITLE
Issue160

### PR DESCRIPTION
**Pull request by benlapETS**
- Added diagrams to our design doc (for message consume|publish process and retry logic)
- Moving code to regenerate chksum each for each time integrity is found seemed to make the system less prone (than master) to get various types of OS errors when running flow test in simultaneous on 2 different machines.

### CODE REVIEW

**Comment by benlapETS** [comment]
I did new tests and I just wonder why is there so many warning from pclean of lags, file not found, etc ?

Also I got the onfly_checksum warning

**Comment by petersilva** [comment]
for *clean* it might be normal to have file not found errors... for others not so much, but there is a fundamentally pathological case:  file with same name published repeatedly, that causes many issues: we publish the first version, it goes through the entire chain, then clean starts deleting, but a second version is partway through the chain...  it is kind of a weakness now that files with static names that get rewritten.

Perhaps we could add a header (at source) to identify such files  'is-rewritten' or 'multi-version' : 'yes' or something, then the flow test could know what to do... this is not fully thought through.  With Michel, we would say 'not baked'  (from the english expression 'half-baked') .... There is perhaps something we could do there, but it needs a little more thought.

I love the diagrams... you should show me the tooling around them to generate them from these sources. It's cool stuff I don't know about.

haven't tested yet...

**Comment by benlapETS** [comment]
the tool is simple, it is call plantuml it uses dot language and graphiz to generate every possible uml diagrams it is directly available on plantuml.com or you may added as plugin to tools like pycharm or even googledoc to generate your diagrams

**Comment by petersilva** [comment]
So I'm unclear on what to do here... I cherry-picked all the the pure diagram commits to master, so they are there, but there is one commit that mixes the diagrams and the code, and I think, from our discussion, the code is wrong, so I didn't pick that.  Then I cherry-picked the last patch, but it doesn't apply cleanly because of the stuff missing from the previous patch.  so I guess the thing to do is for you to  review how I have mangled the diagram in master, and fix it.

Then we can close the pull request.

**Pull request closed without merging**
