### PR TITLE
Completed the plugin factory mechanism for Transfer classes.

### PR DESCRIPTION
**Pull request by benlapETS**
Integrated protocol plugins #356

### CODE REVIEW

**Comment by petersilva** [comment]
looks Cool! Did a run, and it failed... 

```

2020-09-15 17:48:25,792 [DEBUG] sarra.transfer.https credentials sr_http credentials wget://localhost:8090
2020-09-15 17:48:25,792 [ERROR] sarra.transfer.https credentials sr_http/credentials: unable to get credentials for wget://localhost:8090
2020-09-15 17:48:25,792 [DEBUG] sarra.transfer.https credentials Exception details:
Traceback (most recent call last):
  File "/home/peter/Sarracenia/v03_wip/sarra/transfer/https.py", line 145, in credentials
    self.user = url.username
UnboundLocalError: local variable 'url' referenced before assignment
2020-09-15 17:48:25,792 [WARNING] sarra.flow do_download downloading again, attempt 2
2020-09-15 17:48:25,792 [DEBUG] sarra.flow download wget_transport download

`
```

I will try to put an entry in credentials.conf to make it happier.

**Comment by benlapETS** [comment]
> looks Cool! Did a run, and it failed...
> 
> ```
> 
> 2020-09-15 17:48:25,792 [DEBUG] sarra.transfer.https credentials sr_http credentials wget://localhost:8090
> 2020-09-15 17:48:25,792 [ERROR] sarra.transfer.https credentials sr_http/credentials: unable to get credentials for wget://localhost:8090
> 2020-09-15 17:48:25,792 [DEBUG] sarra.transfer.https credentials Exception details:
> Traceback (most recent call last):
>   File "/home/peter/Sarracenia/v03_wip/sarra/transfer/https.py", line 145, in credentials
>     self.user = url.username
> UnboundLocalError: local variable 'url' referenced before assignment
> 2020-09-15 17:48:25,792 [WARNING] sarra.flow do_download downloading again, attempt 2
> 2020-09-15 17:48:25,792 [DEBUG] sarra.flow download wget_transport download
> 
> `
> ```
> 
> I will try to put an entry in credentials.conf to make it happier.

Did you tried this entry
wget://anonymous:anonymous@localhost:8090/

This is the way to make it work for now on my side, I will work on making it work as you want (without the entry).

**Comment by benlapETS** [comment]
Also when we only use the default config for accel_wget_command, we get that:

```
Traceback (most recent call last):
  File "/home/benoit/git/sarracenia/sarra/instance.py", line 207, in <module>
    i.start()
  File "/home/benoit/git/sarracenia/sarra/instance.py", line 199, in start
    self.running_instance.run()
  File "/home/benoit/git/sarracenia/sarra/flow/__init__.py", line 309, in run
    self.do()
  File "/home/benoit/git/sarracenia/sarra/flow/sarra.py", line 31, in do
    self.do_download()
  File "/home/benoit/git/sarracenia/sarra/flow/__init__.py", line 884, in do_download
    ok = self.download(msg, self.o)
  File "/home/benoit/git/sarracenia/sarra/flow/__init__.py", line 1007, in download
    len_written = self.get(msg, remote_file, new_inflight_path,
  File "/home/benoit/git/sarracenia/sarra/flow/__init__.py", line 1065, in get
    return self.proto.do_get(msg, remote_file, local_file, remote_offset,
  File "/home/benoit/git/sarracenia/sarra/plugin/accel_wget.py", line 102, in do_get
    cmd = self.o.accel_wget_command.split() + [
AttributeError: 'Config' object has no attribute 'accel_wget_command'

```

This was puzzling but it makes sense because of a mismatch in the naming, I renamed the config to make it shorter, but I forgot to rename the variable at its declaration. Then when it reach the call: it fails. 

Using automatic refactoring would have prevent this instead of doing it manually but also I should have tested more, like testing all config combinations with rigorous testing (only tested all config or no config), unit test and maybe TDD would have prevented this kind of issue from the beginning of my work.

**Comment by benlapETS** [comment]
2nd try: The config gets is overwritten
```
2020-09-16 20:22:42,128 [INFO] sarra.plugin.accel_wget on_start <sarra.config.Config object at 0x7fe32617f940>
2020-09-16 20:22:42,128 [INFO] sarra.plugin.accel_wget on_start <sarra.config.Config object at 0x7fe32617f940>
...
2020-09-16 20:22:42,242 [INFO] sarra.plugin.accel_wget on_messages <sarra.config.Config object at 0x7fe32617f940>
...
2020-09-16 20:22:42,273 [INFO] sarra.plugin.accel_wget do_get <sarra.config.Config object at 0x7fe32617f130>
```
As we see the object hash code changes, so self.o has been overwritten with an old copy of the config object between on_start and and do_get

**Comment by petersilva** [comment]
after discussion, went a different direction.

**Pull request closed without merging**
