### PR TITLE
Fix sanity not starting missing instances

### PR DESCRIPTION
**Pull request by reidsunderland**
We had a group debugging session and fixed this issue.

### CODE REVIEW

**Review by petersilva — APPROVED** [review]
This will save the government thousands of dollars... because the failure to detect was causing pager calls.

**Comment by petersilva** [comment]
Please Note: We need to document the change in behaviour... with this patch, sr3 sanity will not longer start up "stopped" configs... only "missing" ones.  That's what we decided was least astonishing... but it is still a change from how it worked before.

**Comment by petersilva** [comment]
close #927

**Comment by reidsunderland** [comment]
I think the documentation always said what it was supposed to do. "sanity: looks for instances which have crashed or gotten stuck and restarts them." https://metpx.github.io/sarracenia/Reference/sr3.1.html

**Comment by reidsunderland** [comment]
I grepped for sanity and couldn't find anywhere (in English) that said it started stopped instances, only crashed or stuck instances.

**Comment by petersilva** [comment]
I updated HOWTO/UPGRADING.rst ... to indicate the change in behaviour. same in french ... committed direct to development.
yeah... I old behaviour was a mistake in the first place, but one with seniority.

**Pull request merged**
