### PR TITLE
V03 issue617 (part of it.) "topic" depends more on payload format, than message protocol.

### PR DESCRIPTION
**Pull request by petersilva**
move topic generation away from message protocols and into the payload format code.
the WIS format has a different scheme for determining topic hierarchy, so need a way for the postformat/wis.py to return the "topic" for published messages.

I think the universal idea is that one should be able to determina an appropriate topic from the content of the message.

### CODE REVIEW

**Comment by petersilva** [comment]
las patch fixes the breakage at in the publish API ( #681 )

**Comment by andreleblanc11** [comment]
Looks good. Do we all need to approve the pull request for it to merge?

**Comment by petersilva** [comment]
hey @andreleblanc11 it looks like you have not approved it.. you just put a note in it...
that's a good question... how much review is enough, and what a reviewer should do...
I was just going on if one person reviewed it then that was good enough... but it doesn't show you  reviewed it... so I'm still waiting...  I think you could also "rebase and merge" which is the kind of approval that just makes it go... or you can leave that to me... but some kind of approval would be good.

**Comment by andreleblanc11** [comment]
I think one reviewer is probably enough. We are all so busy with other stuff that having all of us review would be a hassle lol. As for what the reviewer should do.. that is a good question. Maybe there should be some sort of standard to be set? (check the commits, insert appropriate comments, etc.). We can add it to the agenda for the next dev meeting

**Pull request merged**
