### PR TITLE
Update TravisCI to use sr_insects flow_autoconfig

### PR DESCRIPTION
**Pull request by tysonkaufmann**
Created new install.sh script for travis to use to install
 sarracenia and download the sr_insects repo. .travis.yml
 was updated to use this script and call the flow_autoconfig
 script within sr_insects.

### CODE REVIEW

**Comment by tysonkaufmann** [comment]
Seem to be having a permissions issue with the install. Will investigate.

**Comment by tysonkaufmann** [comment]
Updated permissions to install.sh and flow_autoconfig.sh.

Going to wait for the travis job to complete to see if it works!

**Comment by tysonkaufmann** [comment]
Travis runs the tests after changes to permissions. Some tests are failing, but those are issues with the tests themselves.

**Comment by tysonkaufmann** [comment]
Strange. Instead of some tests failing, they seem to be timing out at the end of the flow_limit stage (limit 1000 & limit 3000). This behaviour was not present before. I am going to close this pull request for the time being while I try to diagnose the issue as I am unsure if it is due to these changes.

**Comment by petersilva** [comment]
yes that is one of the existing failure modes.  Run them again a few times...and if they work there is no problem.

**Comment by tysonkaufmann** [comment]
The only way to trigger a rebuild for me is to close and reopen the pull request, so I will try that a couple of times to see if they succeed.

**Comment by tysonkaufmann** [comment]
All tests except flakey_broker have passed at least once over the last couple builds. But flakey_broker has been consistently failing for a while. Should be safe to merge.

**Pull request merged**
