### PR TITLE
To convert, one must wololo

### PR DESCRIPTION
**Pull request by MagikEh**
To convert, one must [wololo](https://knowyourmeme.com/memes/wololo)
wololo priest

### CODE REVIEW

**Review by reidsunderland — CHANGES_REQUESTED** [review]
`logging` should be `logger`

**Comment by MagikEh** [comment]
> `logging` should be `logger`

Lol, copy pasta from further down the file has failed me? xD
https://github.com/MetPX/sarracenia/blob/wolololo/sarracenia/sr.py#L2768

**Comment by andreleblanc11** [comment]
Omg lol

**Comment by andreleblanc11** [comment]
Priority not high enough

**Comment by MagikEh** [comment]
@reidsunderland see 1b2e374

**Comment by petersilva** [comment]
fwiw... logging will work, but it will use a different logger.  that's why the original error isn't caught. it's not invalid... merely wrong.

**Comment by petersilva** [comment]
Looking at the patch it's right after telling us ''converted config exists... federal off"
we could make --wololo an option to overwrite an existing configuration if it exists.

**Comment by petersilva** [comment]
or just make wololo a synonym of convert.

**Comment by MagikEh** [comment]
Lol, I love the option to convert a config in place via `--wololo`.
Synonym makes less sense on the grounds of the player needing to tell their monk to go convert something which is where they then go wololo on it to actually convert it.

I'll spend some time looking into implementing that

**Comment by petersilva** [comment]
fwiw... implementation guide:

* in config.py ... 
   * add "wololo" to *flag_options*   ... will make it work in a config file.
    * add "wololo": False, to *default_options*.  ... will ensure it defaults to False.
    * find the lines with parser.add_argument( '--debug' ... there's three lines make a copy of them and and change --debug to --wololo.   ... will make it work as a command line flag.
* sr.py
   * with the above changes, when you get into sr.py, *options.wololo* will now exist.  So, in the same part of sr.py where you put your original message, look at the if statement above it, and add consideration of that value.  The "wololo" message should be guarded by the if.
  
so... it's less than 10 lines... then have to add an explanation in the docs.

That's just the first option... aka only overwrite an existing option if --wololo is given.

**Comment by petersilva** [comment]
uh... I decided to work on it... it's finished.. writing it up in an issue.

**Comment by petersilva** [comment]
see #1054

**Pull request closed without merging**
