### PR TITLE
Add missing AM headers in amserver

### PR DESCRIPTION
**Pull request by andreleblanc11**
The changes look like a lot but most of them are just indent reformatting's that were done automatically when executing `=G` on vim.

The actual changes are at the end of the `gather`. I recreate the bulletin with the added `CN00 CWAO` on the first line. There's also more verbosity in the code and in the comments

### CODE REVIEW

**Comment by petersilva** [comment]
* In python, an indent is four spaces. period.  That's a hard rule in python style guides. It looks like 8 ? 
* re-formatting is fine. code changes are fine... both in the same patches are verboten.

Please start over with:
* patches that ONLY change the code.
* patches that ONLY re-format.

if they are mixed, it is really hard to understand the changes.
It might be fun to add a setting so that the CN00 default is a settable string.

**Comment by andreleblanc11** [comment]
I forgot to make the bulletin contents be accessible by the message `contents` field. Putting this PR on hold for now

**Comment by andreleblanc11** [comment]
I'll close this PR and create a new one

**Review by petersilva — CHANGES_REQUESTED** [review]
an indent in python is 4 spaces, not 8.
CN00 CWAO should be a settable option.
please have patches with formatting changes and code changes completely separate.

**Pull request closed without merging**
