### PR TITLE
Fix for #1156

### PR DESCRIPTION
**Pull request by mshak2**
Doesn't pass static_flow test on dirt22-2 (33/35 tests passed).

Doing a draft PR to test on github.

Note: In winnow.py, logDuplicates is set to True by default as requested by Jun/Reid

### CODE REVIEW

**Comment by petersilva** [comment]
I disagree with setting options different in different components.  That should be avoided unless there is a really good reason.  Therefore I ask that the default setting be changed in all components, rather than just winnow.

**Review by petersilva — CHANGES_REQUESTED** [review]
don't want different defaults for  winnow vs. other components.
please set this for all.

**Review by petersilva — CHANGES_REQUESTED** [review]
```

'nodupe' in msg['report']['message']:

```
that text will never be in that field... the test should be something like:
```
msg['report']['code'] in [ 304 ] 

```
perhaps add codes later (discussion) ...

**Comment by petersilva** [comment]
Looking over things... this patch only covers the winnow case, not the general subscription.  In general subscriptions there is a second point where duplicate suppression happens... just before a file is downloaded, if it would overwrite an existing one, it is checked... and a 304 rejection done if they are considered the same.

(can see this in flow/__init__.py/file_should_be_downloaded... )

So I think a second part of this improvement should be to check for duplicates in after_work, in addition to after_accept.

**Comment by petersilva** [comment]
fwiw... I just ran the original branch on my wsl, and it passes.  Still want some changes though.  will re-run later.

**Review by petersilva — CHANGES_REQUESTED** [review]
There was another required change... have the same stuff done to after_accept also done to after_work in log.py because some rejections for duplicate happen in the download phase.

**Comment by petersilva** [comment]
The request was to make rejects only of duplicate suppression be logged, but not rejections for any other reason.  I looked for 304 in the sarracenia/flow/__init__.py and there are:
```

     self.reject(
                                m, 304, "mask=%s strip=%s url=%s" %
                                (str(mask), strip, urlToMatch))

```

```

               self.reject(msg, 304,
                            "mtime not newer %s " % (msg['new_path']))

```

need to change the numbers for those.

**Comment by mshak2** [comment]
> The request was to make rejects only of duplicate suppression be logged, but not rejections for any other reason. I looked for 304 in the sarracenia/flow/**init**.py and there are:
> 
> ```
> 
>      self.reject(
>                                 m, 304, "mask=%s strip=%s url=%s" %
>                                 (str(mask), strip, urlToMatch))
> ```
> 
> ```
> 
>                self.reject(msg, 304,
>                             "mtime not newer %s " % (msg['new_path']))
> ```
> 
> need to change the numbers for those.

So first one should be 404, and second one should be 406?

**Comment by petersilva** [comment]
@mshak2 there are conflicts with development branch. Can you merge dev to this branch so the conflicts get resolved?

**Review by petersilva — APPROVED** [review]

**Pull request merged**
