### PR TITLE
Issue974 yet another scheduled_poll refactor PR

### LINKED ISSUE #974: Redesign poll to work like scheduled flow? (Because polls do not consume from queues until after sleeping for a long time)
When a poll is running in a cluster, each node subscribes to messages posted by the node with the VIP to populate their duplicate suppression caches.

The problem is that the poll works like this:

1. Gather (poll for new messages and consume from queue)
2. Post messages received from the poll routine
3. Sleep
4. Repeat

This means that messages posted by the poll routine are not consumed from the queue until after the sleep.

For example, here's the queue of a poll with `sleep 15m`:
image

This isn't ideal, especially on polls that have a long sleep time and post a lot of messages. A poll with `sleep 1h` that posts 10,000 messages each time it runs would leave 10,000 messages × *n* nodes on the broker for an hour at a time.

Other components (usually) don't sleep for very long, so they always consume from the queue.

--- 

@petersilva, @andreleblanc11 and I discussed this, and we're considering changing the poll to work like like a [scheduled flow](https://github.com/MetPX/sarracenia/blob/development/sarracenia/flowcb/scheduled/__init__.py). 

The difference between a scheduled flow:

- Poll *polls* a source server and produces a new/different list of files/messages each time. 
- Scheduled flow posts the same files each time. 

But the scheduling would be the same: the user could either set a `scheduled_interval` (would replace the current `sleep` interval *just for polling*) or define `scheduled_hour` and `scheduled_minute`.

With this, the poll component would use `sleep` like the other components and just sleep for a short amount of time, and the poll would be scheduled separately.  The [Message](https://github.com/MetPX/sarracenia/blob/development/sarracenia/flowcb/gather/message.py) gather routine would run more often than the poll (every sleep interval) and the . 

We also get the benefit of being able to schedule polls to run at specific hours and minutes, which isn't an option we currently have.

### PR DESCRIPTION
**Pull request by petersilva**
closes #974 

This is a third PR ( of the poll refactor work, replacing https://github.com/MetPX/sarracenia/pull/985 (which in turn replaced another one) which had five separate commits, that individually do not pass the flow tests, so would break git bisection. Want to keep bisection working, so re-created the branch with those five commits squashed together.

Once that was done, added a refactor of the Flow class's (sarracenia.flow.Flow) run() routine.  It was very long (288 lines) 

  * made called routines for flow algorithm phases:  *gather, filter, work, post* routines  more responsible (moved code into them.)
  * the phase routines now call the relevant plugin entry points
  * the phase routines now re-arrange the worklists.
 
Once the run() routine was shortened (to 155 lines... better, but not really good... enough to understand the algorithm) it felt safe to re-arrange algorithmic flow so that a "poll" can now download, identically to other components.  (the *work* phase used to not be run when running a poll.)

comments from original PR (with annotations for what was tackled):

* It doesn't do a poll on startup, currently. it waits for one interval before the first poll. easy to fix... should we?
  (**FIXED** by:  3e4ba34c0efa600ba9fef274127b2f298f005228 , adjusted by: 06fa2d36089634a02d9bd82c32a22cadc1499a44 )

So now in poll, the loop towards the end of the run() routine is only used to sleep for 1 second at a time... and the real waiting is done in the scheduled.poll plugin instead.

*  In watch... still using long sleeps in that loop at the end... Is this an opportunity to simplify sr_watch also... so it also uses the same methods? Is there an advantage to doing it that way?

* I'm wondering if there is a way to have watch use a shared duplicate suppression cache the same way as poll does, 
   populating itself with the output exchange binding queue. Same benefit as poll, run on two machines with a vip and 
   failover. (not done...)

* wondering if this change might be an opportunity to simplify sarracenia.flow/init.py run() routine. It feels too complicated.
   (**DONE** 71fe41d9e52947282398c1d0132771a778275933 ac9b1026f4b260d256a7815a68971bf96e31bfe4 32b2554627e769f865ee088ea353302244982c0f 06fa2d36089634a02d9bd82c32a22cadc1499a44 52219cd2194681826df755fd2deb2b34ae89f0ad )    Now poll runs work() aka do() so if "directory" were normal... it could be used by poll, see other PR  https://github.com/MetPX/sarracenia/pull/987

### CODE REVIEW

**Comment by petersilva** [comment]
this one should not be squashed... just merged in...

**Comment by petersilva** [comment]
OK this looks ok now, a merge should be clean.

There is a problem I ran into where options not declared in the main routines don't get parsed with the right types (opened as #992) there is a fix in this PR for that.  Had the same problem working with @mshak2 
this week where a add_option thing (a flag in that case) had the wrong type.

It was needed because scheduled_interval was such a value, and it was getting a string value, and ... silly.
so now, when converting a poll from v2 to sr3 the sleep setting is converted as scheduled_interval.
the defaulting still happens, but only if none of the scheduled* options are set.

all the commits are in an order that supports clean git bisection.

**Comment by petersilva** [comment]
oh... and for testing purposes the branch to look at is https://github.com/MetPX/sarracenia/tree/issue974

**Comment by reidsunderland** [comment]
It looks like the option parsing change broke the logEvents setting in the flow test?

**Comment by petersilva** [comment]
> It looks like the option parsing change broke the logEvents setting in the flow test?

it's fixed already.   ( 7ed95572886b8ad6b3222e862158687924e2d359 ) 

I did a forced update to back out a commit, then re-ordered things so the tests never fail.

**Comment by petersilva** [comment]
found some more issues with set parsing working with Mathew.
more patches inbound.

**Comment by petersilva** [comment]
@reidsunderland we looked at all the commits together (with @andreleblanc11 ) and we accepted all the other PR's.
merged those into this branch. So it should be really good to do... Would appreciate a last round of testing before we merge it back into development.

Thanks.

**Comment by petersilva** [comment]
OK looking ok after the weekend.  after discussion, merging.

**Pull request merged**
