### PR TITLE
adding class so octal values print intuitively.

### PR DESCRIPTION
**Pull request by petersilva**
this came up... with this code, sr3 show displays
```
'permDefault': o0,
 'permDirDefault': o775,
 'permLog': o600,


```

### CODE REVIEW

**Comment by petersilva** [comment]
OK original version was buggy... I thought it was too simple to bother testing... but it was me that was too simple... all the flow tests fail, it turns out python doesn't convert things to int without you telling it to so have to add conversions at all makedirs and chmod calls in the code.

patches coming...

**Comment by reidsunderland** [comment]
What if you make class octal_number inherit from the built in int, and just override the __str__ and __repr__ methods?

**Comment by reidsunderland** [comment]
```python
class octal_number(int):
    def __repr__(self) -> str:
        return oct(self)

    def __str__(self) -> str:
        return oct(self)

test = octal_number(0o755)
print("octal", test)
print("decimal", int(test))
```

Output:

```
octal 0o755
decimal 493
```

**Comment by petersilva** [comment]
With @reidsunderland's comment reverted the previous commit that was converting everything.

**Comment by petersilva** [comment]
Sigh...  for documentation purposes, after the merge, I don't understand why things were passing, but for what it's worth, tests started failing later, so I had to add a __new__ routine, and that fixed things...  It was doing this:

```

Traceback (most recent call last):
  File "/home/peter/Sarracenia/sr3/sarracenia/instance.py", line 248, in <module>
    i.start()
  File "/home/peter/Sarracenia/sr3/sarracenia/instance.py", line 239, in start
    self.running_instance.run()
  File "/home/peter/Sarracenia/sr3/sarracenia/flow/__init__.py", line 491, in run
    self.do()
  File "/home/peter/Sarracenia/sr3/sarracenia/flow/subscribe.py", line 27, in do
    self.do_download()
  File "/home/peter/Sarracenia/sr3/sarracenia/flow/__init__.py", line 1549, in do_download
    if self.mkdir(msg):
  File "/home/peter/Sarracenia/sr3/sarracenia/flow/__init__.py", line 1395, in mkdir
    mode=int(mode,base=8)
TypeError: int() can't convert non-string with explicit base
fractal%

```

fixed with 89a18c5427f153cbb6caa330b26685636e1efc79

**Pull request merged**
