### PR TITLE
Issue166

### PR DESCRIPTION
**Pull request by benlapETS**
Completed the v03 spec + some enhancements and cleanup

### CODE REVIEW

**Comment by petersilva** [comment]
it is a cleanliness thing... https://pythonhosted.org/watchdog/quickstart.html
I think removing the join has no effect, but I worry about leaving crumbs around in the OS because we don't cleanup after ourselves.

I will merge anyways if it passes the test, but rationale needed.

**Comment by petersilva** [comment]
looking at logs from the flow test, I see incorrect field values:

r_winnow_t01_f10_01.log:2019-03-08 09:10:08,390 [INFO] post_log notice=20190308140907.677624 http://dd5.weather.gc.ca /citypage_weather/xml/NS/s0000264_e.xml headers={'mode': '644', 'source': 'WXO', 'to_clusters': 'ALL', 'sum': 'd,fcc4cd41965c81982673b7041bfffb95', 'parts': '1,30237,1,0,0', 'from_cluster': 'WXO', 'mtime': '20190308140907.0737845898', 'atime': '20190308140907.0737845898', 'size': '0'}

Where does this size header come from?  This is a v02 message.  V02 messages should not have v03 headers in them and vice-versa.  I find 'size=0' through lots of logs... should not be there.

v02 should have a *parts* header.   v03 should have only a *size* header if partitioning strategy is 1, and an additional 'block' (blocking? don't remember) if there is inplace or partitioned  *parts* header in the corresponding v02 message.

**Comment by petersilva** [comment]
not merging for now because of  size=0, and also the unexplained loss of observer.join.

**Comment by benlapETS** [comment]
For the observer.join it was unreachable code so it has never been executed and it will never be as is, I saw it as dead code.
For the v02 I need to investigate, I dont understand why it happens...

**Comment by benlapETS** [comment]
Ok both branch issue160 and issue166 are ready to be merge. Be careful as I force updated issue160, also merging issue166 will raise a merge conflict be sure to keep only changes from issue166...

**Pull request merged**
