### PR TITLE
Issue223

### PR DESCRIPTION
**Pull request by benlapETS**
Completed most of the changes I wanted to operate in pcleans

### CODE REVIEW

**Comment by petersilva** [comment]
I don´t know what is going on, nothing is passing... getting between 12 and 14 of 23 tests passing...
can´t really merge that for now... I´m looking at things, but it isn´t clear what to do...

**Comment by petersilva** [comment]
I´m looking at this one first:

`test 11 FAILURE: no successful results! sr_post test2_f61	 (0) should have half the same number of items of sr_sender 	 (5874)
`

**Comment by benlapETS** [comment]
I forced pushed this branch maybe it has diverged since you fetched it and you maybe you have my change to sr_post which I removed??

**Comment by petersilva** [comment]
yup, that patch was still there.  deleted my local branch, and pulled fresh from origin.
now the shim is OK,  then I changed the C stuff to use v02 instead of v03 and it is working
again, and removed MSC-SAT just to clean the tests in this branch...

but there are still three tests that fail always:
```

test  3 FAILURE: sr_sarra	 (701) should have the same number of items as winnows'post	 (1039)
test 14 FAILURE: sr_shovel pclean_f90 (701) should have the same number of watched items winnows' post	 (1039)
test 15 FAILURE: sr_shovel pclean_f92 (701) should have the same number of removed items winnows' post	 (1039)

```

so I get 20 of 23.   tried it twice... bad result is reproducible.
I will try the other one first, and then come back?

**Comment by benlapETS** [comment]
I am about to push a branch with 240-223-227 already merged

**Pull request closed without merging**
