### PR TITLE
Add Ubuntu 22.04 to v2 flow tests

### PR DESCRIPTION
**Pull request by reidsunderland**
edited

### CODE REVIEW

**Comment by reidsunderland** [comment]
I just wanted to see if the tests for v2 would work on 22.04

**Comment by petersilva** [comment]
There are options to skip tests that are known to fail ... I forget what they are though...
It should be obvious in the flow_check scripts... something like SKIP

**Comment by petersilva** [comment]
oh... and all yesterday 20.04 was borked... the other os´s were passing, but 20.04 failed.  retried this am, and ok.

**Comment by reidsunderland** [comment]
The Actions yml file has V2SKIP_KNOWN_BAD set to yes, but I don't see that used in sr_insects. Is it flow_check supposed to use it on the broken v2 tests?

**Comment by petersilva** [comment]
yeah... it is... I was looking at tests that I knew were borked and knew we did not have time to address and had put a guard around them so v2 tess would work... I guess that got lost somehow?

**Comment by reidsunderland** [comment]
maybe you forgot to push the change or it got lost with computer switches? 

We could just remove flakey (and dynamic? I forget if it's supposed to be working) from the v2 yml file?

**Comment by petersilva** [comment]
I just looked... V2_SKIP_KNOWN_BAD looks set up correctly in my version of insects... hmm... I'm on the main branch...

**Comment by reidsunderland** [comment]
It's `V2SKIP_KNOWN_BAD` in the yml and I only grepped for that...

```
$ grep -ir KNOWN_BAD .
./flakey_broker/flow_check.sh:if [ "${SKIP_KNOWN_BAD}" ]; then
./static_flow/flow_check.sh:if [ "${SKIP_KNOWN_BAD}" ]; then
./static_flow/flow_check.sh:if [ "${SKIP_KNOWN_BAD}" ]; then
./dynamic_flow/flow_check.sh:#if [ "${V2_SKIP_KNOWN_BAD}" ]; then
./dynamic_flow/flow_check.sh:if [ "${V2_SKIP_KNOWN_BAD}" ]; then
./restart_server/flow_check.sh:if [ "${SKIP_KNOWN_BAD}" ]; then
```

**Comment by petersilva** [comment]
I'm not sure of the difference between SKIP_KNOWN_BAD and V2_SKIP_KNOWN_BAD ...

**Comment by reidsunderland** [comment]
I updated the yml again to have `V2_SKIP_KNOWN_BAD` and `SKIP_KNOWN_BAD`. I guess you might have been working on this when flakey was still broken for v3

**Review by petersilva — APPROVED** [review]
can't make things any worse than today.

**Pull request merged**
