### PR TITLE
Issue255

### PR DESCRIPTION
**Pull request by benlapETS**
Just another attempt to merge sr_amqp tests. You (or we) may want to review sr_amqp together...

### CODE REVIEW

**Comment by petersilva** [comment]
On the choice of the word *method* ... yeah... it is not our fault.. blame AMQP.
That trips me up also...  I was confused and looked it up.
 from: https://www.rabbitmq.com/tutorials/amqp-concepts.html
```

AMQP 0-9-1 Methods
AMQP 0-9-1 is structured as a number of methods. Methods are operations (like HTTP methods) and have nothing in common with methods in object-oriented programming languages. Protocol methods in AMQP 0-9-1 are grouped into classes. Classes are just logical groupings of AMQP methods. The AMQP 0-9-1 reference has full details of all the AMQP methods.

Let us take a look at the exchange class, a group of methods related to operations on exchanges. It includes the following operations:
```

I think it refers to a packet format... describing a certain packet sent in one direcfion or the other.  I suppose that would correspond to a python tuple.  It is kind of confusing when they refer to the return value of a function as a method... but I supposed it follows.

**Comment by petersilva** [comment]
The branch isn't uptodate with master... there are conflicts... please bring it upto date...

**Comment by benlapETS** [comment]
it is up to date, you surely have an old version of the branch in your local git, please dont merge it in to your local git as it will screw up the work. The valid version is on github. If you still want to test it in local you have to reset the branch in your local git, do it like that:

```
git fetch
git reset --hard origin/issue255
```

**Comment by petersilva** [comment]
uh... ok... this pull request on github tells me *this branch cannot be rebased due to conflicts* ...  any ide what that is about... nothing to do with my stuff.  But yeah, my repo was messed up worse... I did the checkout as recommended... and it does look better, but doesn´t explain the weirdness here...

**Comment by benlapETS** [comment]
I don't understand why you are trying to rebase ? have you tried to merge instead ?

**Comment by benlapETS** [comment]
And for the method it is called a namedtuple, though my comment wasn't explicitly detailing my finding on that.

> On the choice of the word _method_ ... yeah... it is not our fault.. blame AMQP.
> That trips me up also... I was confused and looked it up.
> from: https://www.rabbitmq.com/tutorials/amqp-concepts.html
> 
> ```
> 
> AMQP 0-9-1 Methods
> AMQP 0-9-1 is structured as a number of methods. Methods are operations (like HTTP methods) and have nothing in common with methods in object-oriented programming languages. Protocol methods in AMQP 0-9-1 are grouped into classes. Classes are just logical groupings of AMQP methods. The AMQP 0-9-1 reference has full details of all the AMQP methods.
> 
> Let us take a look at the exchange class, a group of methods related to operations on exchanges. It includes the following operations:
> ```
> 
> I think it refers to a packet format... describing a certain packet sent in one direcfion or the other. I suppose that would correspond to a python tuple. It is kind of confusing when they refer to the return value of a function as a method... but I supposed it follows.

**Comment by benlapETS** [comment]
Forget (and forgive) my comment on the method thing, this is for pika and I didn't test pika...

**Comment by petersilva** [comment]
the thing I am looking at is the removal of the  msg_count == -1 code... how do we know it will never return -1. I saw in some comment somewhere the -1 was something we put in ourselves... going over git log... OK you removed it almost a year ago, and before were were catching the exception in declare, now we just let it fail out to the thing calling declare... still loops... OK.. no net change.

**Comment by petersilva** [comment]
umm... how to I run ...   tesr_sr_amqp.py ?

**Comment by benlapETS** [comment]
I did not remove the -1, I think you did in this commit f888fc30.

To run the test:
python -m unittest tests.test_sr_amqp.suite

**Comment by petersilva** [comment]
you're right I removed the -1 in the inner routine..  but once that was done, it made good sense to remove the -1 on the other end, as you did.   My git repo was in a strange state,  just cloned a new one, now  It says:
 ModuleNotFoundError: No module named 'tests.test_sr_amqp'

not sure what environment is supposed to be...

**Pull request merged**
