### PR TITLE
sr_subscribe only a fraction of (hourly, not minute) the swob xml files by conf. file

### PR DESCRIPTION
**Pull request by Ruthou**
Hi, I am seeking help to rewrite the conf. file to receive and download the hourly swob files only. 
I used "swob_example.conf" and defined the particular station I needed. But I am not able to use wildcard to define receiving the hourly files only, or reject minute files.

Please help. Here below is the last portion of my conf. file, which works and pulling in all minute and hour files. 

# Only station CVKC
  subtopic observations.swob-ml.*.CVKC.#
accept .*

Thank you.

### CODE REVIEW

**Comment by petersilva** [comment]
This pull request is very confused... it is trying to merge v03_wip (a total re-write) back to main (v2.) which would involve many thousands of changed.  I'm closing this without merging.   To accomplish what you want, you can just take the normal example and add:

```
    reject .*AUTO-minute-swob.xml.*

```

**Comment by Ruthou** [comment]
Thank you, Peter. Sorry about the confusion. I will try the suggestion you gave me and let you know.

________________________________

**Comment by petersilva** [comment]
oh... and the reject needs to be above the accept in the line.

**Comment by Ruthou** [comment]
Hi, Peter,

Please take a look at my conf below. I am so new to programming...


Thanks a lot.

Ruth

# Fichiers d'observations en format SWOB
# Pour plus d'information sur ce produit, veuillez consulter la documentation a
# http://dd.meteo.gc.ca/observations/doc/README_SWOB.txt

broker amqps://dd.weather.gc.ca/

# Observation files in SWOB format
# For more information about this product, please consult the documentation at
# http://dd.weather.gc.ca/observations/doc/README_SWOB.txt

#instances:
#    quantité de processus qui téléchargent simultanément.
instances 2
#instances: number of downloaders running. If you see lag in the log, increase.

#expire, en usage opérationnel, c´est mieux 1d (1 jour) pour celui-ci. Il faut
#     que ça soit plus long que l´interru ption le plus long qu´on veut
#     tolérer sans perte.
expire 2h
#expire, in operations, needs to be longer than the longest expected interruption

# All stations
# subtopic observations.swob-ml.#

# Only station CVKC
  subtopic observations.swob-ml.*.CVKC.#
reject .*AUTO-minute-swob.xml.*
accept .*

________________________________

**Comment by Ruthou** [comment]
Hi, Peter,

Nothing flew in with the modified conf below, neither the hourly file or minutes files (which were rejected and not supposed to be in)

Can you help please?

Many thanks

Ruth


# Fichiers d'observations en format SWOB
# Pour plus d'information sur ce produit, veuillez consulter la documentation a
# http://dd.meteo.gc.ca/observations/doc/README_SWOB.txt

broker amqps://dd.weather.gc.ca/

# Observation files in SWOB format
# For more information about this product, please consult the documentation at
# http://dd.weather.gc.ca/observations/doc/README_SWOB.txt

#instances:
#    quantité de processus qui téléchargent simultanément.
instances 2
#instances: number of downloaders running. If you see lag in the log, increase.

#expire, en usage opérationnel, c´est mieux 1d (1 jour) pour celui-ci. Il faut
#     que ça soit plus long que l´interru ption le plus long qu´on veut
#     tolérer sans perte.
expire 2h
#expire, in operations, needs to be longer than the longest expected interruption

# All stations
# subtopic observations.swob-ml.#

# Only station CVKC
  subtopic observations.swob-ml.*.CVKC.#
reject .*AUTO-minute-swob.xml.*
accept .*


________________________________

**Comment by petersilva** [comment]
That looks find, before the accept you might want to have a line like:

directory /tmp/kk

to have the files put in the /tmp/kk directory.  With the config as is, it looks like it will put things in the directory you are in when you call sr_subscribe.

**Comment by petersilva** [comment]
fwiw: the "normal" thing most people would expect would be to open an issue for this type of question/answer, rather than making a pull request.

**Comment by Ruthou** [comment]
Sorry about that, Peter. I am so new to this programming world, and this is my first time to ask help online.

I browsed most of the issues in github and did not find any of the answers I need. (Probably my issue would not be an issue to most the programmers). I thought about submitting an issue, a second thought is : this is more a lack of skills of my programming language, not an issue. That is why, I pulled a request, thinking this is just "ask for help" as it sounds so in common environment.

I am so happy to let you know it seems working. I just received my first hourly file with your help, by retriggering the bash. (I have no idea why it is not working since yesterday)

[cid:a2ae9c01-94d9-4c15-ae09-1dcfd4e6539e]

I am very grateful.

In addition, if you can guide me how to reject some elements in xml file, that would be wonderful. I don't need all the elements provided there. Running them all in is unnecessary.

Thank you very much

Ruth

________________________________

**Comment by petersilva** [comment]
You're very welcome!  I'm glad you got what you need so far. Sarracenia transfers products... which are entire files... but there are many different kinds of files, so we we try not to know about what is in the products. To get help with the products themselves, you would need contact ECCC.  This is perhaps a good start:

https://eccc-msc.github.io/open-data/msc-datamart/readme_en/

**Comment by Ruthou** [comment]
appreciate all your help, Peter. Enjoy the rest of your weekend!

Ruth

________________________________

**Pull request closed without merging**
