### PR TITLE
add Docker capability

### PR DESCRIPTION
**Pull request by tomkralidis**
Adds Docker setup and sample Docker Compose workflow.

### CODE REVIEW

**Comment by petersilva** [comment]
um... would prefer "pump" rather than "watch" with the entire config directory mapped and the ability to run a number of configurations in the same container... is it better to acccept the pull and change it after? or should it be changed first?
It still references an individual watch config file instead of the whole directory, and it doesn't persist the logs or statefiles.

**Comment by petersilva** [comment]
thinking more about that... do we want the config files to be outside the container as well?

**Comment by tomkralidis** [comment]
Thanks; I've pushed some changes to address some feedback.  Where are the statefiles usually placed in an sr3 install?

Having said this, the `docker/compose` setup is there as an example.

**Comment by petersilva** [comment]
~/.cache/sr3

**Pull request merged**
