### PR TITLE
Finalize Azure Transfer tests

### PR DESCRIPTION
**Pull request by gcglinton**
Managed to write the last few tests for the Azure Transfer driver, using [Testcontainers](https://testcontainers.com/), specifically the [Azurite](https://testcontainers-python.readthedocs.io/en/latest/modules/azurite/README.html) one.

It spins up a container for every test function in the file, and then destroys it, so the state is clean, and well defined between tests.

It takes quite a long time to run, compared to the S3 tests, or any others, because it's having to do a lot of work in the background for each test. It might be possible to optimize things, but using different "containers" (in Azurite, not a Docker container), re-using the same Testcontainer, but that would need a bit more work to setup for each test.

*edit:* Going to see if that last idea is viable...

### CODE REVIEW

**Comment by gcglinton** [comment]
Was able to re-work the tests per my last paragraph.

It now only creates a single instance of Azurite for the whole test module.

Each test function then creates it's own storage container (in Azurite, not a docker container), and creates the same blobs, so that the environment is uniform across tests.

It took the runtime down from 2m40s, to just around 1 minute.

**Comment by gcglinton** [comment]
Closes #1015, and related to #1016.

**Comment by petersilva** [comment]
So... I checked out the branch, and merged from development, and pip3 install -r requirements.txt, and it fails very long...

The summary is:
```
tests/sarracenia/transfer/azure_test.py ......FEE..E.E.EE.  

```

the very long complaints are lots of occurrences of:
```

../../.local/lib/python3.10/site-packages/urllib3/connectionpool.py:703: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.local/lib/python3.10/site-packages/urllib3/connectionpool.py:398: in _make_request
    conn.request(method, url, **httplib_request_kw)
../../.local/lib/python3.10/site-packages/urllib3/connection.py:239: in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
/usr/lib/python3.10/http/client.py:1283: in request
    self._send_request(method, url, body, headers, encode_chunked)
/usr/lib/python3.10/http/client.py:1329: in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
/usr/lib/python3.10/http/client.py:1278: in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
/usr/lib/python3.10/http/client.py:1038: in _send_output
    self.send(msg)
/usr/lib/python3.10/http/client.py:976: in send
    self.connect()

```

other occurrences of:

```
E           requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

../../.local/lib/python3.10/site-packages/requests/adapters.py:501: ConnectionError

```
            ) from e
E           docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

../../.local/lib/python3.10/site-packages/docker/api/client.py:230: DockerException


```

```
E       FileNotFoundError: [Errno 2] No such file or directory

../../.local/lib/python3.10/site-packages/docker/transport/unixconn.py:26: FileNotFoundError


```

what file is missing where is the question I guess.  running this on ubuntu 22.04.

**Review by petersilva — APPROVED** [review]
works better with docker installed ;-)

**Pull request merged**
