### PR TITLE
fixing Issue #839 - fixing positional grouping in sr3

### PR DESCRIPTION
**Pull request by petersilva**
This branch fixes an incompatibility with v2, where position parameter matching using regexes works.
 
* added some unit tests to config_test.py with single and multiple positional parameters.
* capture the match resturned by re.match when processing an accept line.  store it in a message field.
* add a loop to variableExpansion() to to substitutions using the matching field.
* implement a new setting: *self.sundew_compat_regex_first_match_is_zero*
  setting is needed, because the natural thing, is to have regexes work like python match & groups.
 
unrelated fix also in the same branch:
* stop printing queue declare if passive==True, as it's spamming the logs.

### CODE REVIEW

**Comment by petersilva** [comment]
discussed... agreed.

**Comment by gcglinton** [comment]
Not that anyone asked, but my $0.02 is that regression tests, or tests that are meant to validate a specific fix, should be pulled out into their own tests.

The name of the test set could have the PR/issue number referenced in them. `test_variableExpansion_pr839`, or `test_variableExpansion_issue839`

At the very least, I suggest to mention it in the comments for a given set of asserts, otherwise it might seem that some tests overlap, and could lead to removal of those specific conditions down the road.

**Comment by petersilva** [comment]
wait... tests have names? We could add issue references... that would be cool!  how does one name tests?

**Comment by gcglinton** [comment]
Yeah, each function/class inside a `*_test.py` file is it's own "test set". So in this case you can just create a new function called `test_variableExpansion_issue839`, and put the tests for just that issue in there, and voila, a well-identified regression test.

The other option, if a regression test covers a number of functions, would be to create a class for them, and group them that way.

With that pattern, tests that are wholly contained within a single module, but span various functions, I'd suggest putting the the test class in the module test file.
However tests that touch a number of modules (and would therefore normally be split across a number of test files to ensure consistency with the idea of "1 file, one module") could live in their own `Test_Regressions` class in a `regression_test.py` file at the root of the `test/sarracenia` directory.

For naming, the classes must start with `Test_` for PyTest to pick them up properly, so in this case, you could create a class called `Test_Regressions`, which would then contain a function called `test_issue839`. Because test names are "fully-qualified" so to speak, the full name of the test contains the path to the test file, the class name, and function name. In this particular case, since the regression test just affects `config.py`, it'd be `sarracenia/config_test.py::Test_Regressions::test_issue839`, or something to that effect.

Personally, I'd go with the class way, as I think it makes the most sense, keeps regressions grouped, well identified, and the pattern can work across multiple files if needed.

The other way of doing this is with [markers](https://docs.pytest.org/en/7.1.x/example/markers.html), but those aren't as obvious to report on, or notice.

**Pull request merged**
